# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Website CI

on:
  push:
    branches:
      - develop
      - main
      - feature/**
      - hotfix/**
      - release/**
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Deno
      run: curl -fsSL https://deno.land/install.sh | sh

    - name: Install Python
      run: |
        sudo apt update
        sudo apt install -y python3-pip

    - name: Initialize www production directory
      run: |
        mkdir www
        cp favicon.png www/
        cp index.html www/
        cp -R assets www/
        cp -R files www/

    - name: Build blog
      working-directory: blog
      run: |
        deno task build
        cp -R _site ../www/blog

    - name: Build complete resume
      working-directory: complete-resume
      run: |
        pip install "rendercv[full]"
        rendercv render "thomas-cicognani-complete-resume.yaml"
        cp rendercv_output/Thomas_Cicognani_CV.pdf ../www/files/thomas-cicognani-complete-resume.pdf

    - name: Replace IP address in files
      working-directory: resume
      run: |
        current_ip=$(hostname -I | awk '{print $1}')
        echo "Current IP address: $current_ip"
        find . -type f -exec sed -i "s/\[your-server-ip\]/$current_ip/g" {} +

    - name: Launch Docker Compose for reactive resume
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./resume/docker-compose.yml"

    - name: Build resume
      working-directory: resume
      run: |
        echo "TODO"
        cp ../www/files/thomas-cicognani-complete-resume.pdf ../www/files/thomas-cicognani-resume.pdf

    - name: Save production directory
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: www
        path: ./www/
        retention-days: 5

    - name: Dump docker logs
      if: ${{ failure() }}
      uses: jwalton/gh-docker-logs@v2

  test:

    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Get www production directory
      uses: actions/download-artifact@v4
      with:
        name: www

    - name: Playwright tests
      run: echo "TODO"

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: playwright-report
        path: ./Shop-E2E/playwright-report/
        retention-days: 5

    - name: Upload Playwright snapshots
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: playwright-snapshots
        path: ./Shop-E2E/tests/resources/snapshots
        retention-days: 5

  deploy:

    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == "main" }}

    steps:

    - name: Get www production directory
      uses: actions/download-artifact@v4
      with:
        name: www

    - name: Install ftp
      run: |
        sudo apt update
        sudo apt install -y lftp

    - name: Upload static website
      working-directory: www
      run: lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rev ./ ./ --ignore-time --parallel=10"
